### ISSUE TITLE
`EPOLL_CTL_ADD` used when trying to modify a file descriptor

### ISSUE THREAD

**Issue by weissi** [mheily/libkqueue#29]
basically if a file descriptor is first only used for reading (`EPOLLIN`) and later on switches to reading and writing (`EPOLLOUT`), there's currently no way to modify the epoll set as `EPOLL_CTL_ADD` is used unconditionally (but it should be `EPOLL_CTL_MOD`). Full details here: https://bugs.swift.org/browse/SR-3360

**Comment by LubosD** [comment]
Also encountered under Darling macOS emulation. The problem is the descriptor is added into 2 different filters and libkqueue has no idea the fd has already been added into epoll.

**Comment by LubosD** [comment]
This is my solution: https://github.com/darlinghq/darling-libkqueue/commit/67c22f96ce53887e81af2837894968f09770e0ff

The idea is to `dup()` every fd before adding it into epoll, since otherwise we cannot have the same fd in epoll twice with possibly different flags (oneshot and/or edge triggered).

If the application using kqueue expects fds to be automatically removed from kqueue when closed, more hacks will be required to mimick the behavior.

**Comment by arr2036** [comment]
This surprises me as there should be one epoll instance per kqueue/filter.  Could you provide some example code to reproduce the issue?

**Comment by LubosD** [comment]
`filter_epfd()` gets the epoll file descriptor from the kqueue object, so there is just one such instance.

**Comment by arr2036** [comment]
Ugh, you're right. OK, well I guess we *should* maintain separate epoll instances for each filter.  I don't think there's really an issue with that other than we burn an extra fd per kqueue.

**Comment by alexhultman** [comment]
I tried using libkqueue as an alternative to buying an overpriced Apple computer only to have the kqueue API. libkqueue does not work for my application as, just like pointed out here, EV_ADD translates to EPOLL_CTL_ADD and not (EPOLL_CTL_ADD/EPOLL_CTL_MOD). This makes it basically impossible to implement the most basic network application as the flow goes like this:

* connect gives you an FD
* start polling for writable on that FD (adds the FD to epoll)
* when writable, modify it to poll for readable (fails with EEXIST since libkqueue already added the FD)
* now the app is broken

**Comment by bombwork** [comment]
Kqueue isn't osx exclusive feature. 

> Kqueue is a scalable event notification interface introduced in FreeBSD 4.1 on July 2000,[1][2] also supported in NetBSD, OpenBSD, DragonFly BSD, and macOS.

Additionally FreeBSD allows to crosscompile apps for osx
