### ISSUE TITLE
Moving libkqueue forward

### ISSUE THREAD

**Issue by arr2036** [mheily/libkqueue#40]
The FreeRADIUS project has adopted libkqueue as the primary eventing system on Linux and Solaris.

We now have four outstanding pull requests for various issues, but haven't see any response from the maintainer (@mheily).  He does not appear to have been active since January this year.

We would rather not have to fork this project to continue development, but as the number of unpatched issues increases, the difficulty on maintaining multiple pull requests in parallel will force us to do so.

In the mean time, our temporary fork is available here: https://github.com/FreeRADIUS/libkqueue

It contains fixes for outstanding issues we've identified.  If users/developers also working with/submitting patches to libkqueue, they may also wish to open a pull request against our repository.

If our temporary fork becomes permanent (six months from now if no response from @mheily is received), then we'll also pull in any outstanding fixes from this repository.

---

FreeRADIUS was founded in June 1999 by Miquel van Smoorenburg and Alan DeKok. The first public "alpha" release of the code was in August 1999, with 0.1 being released in May 2001. Since then, new versions have been released every few months.

FreeRADIUS is used daily by 100 million people to access the Internet.

The project has grown to include support for more authentication types than any other open source server. It is used daily by 100 million people to access the Internet. There are over 50 thousand sites using FreeRADIUS, ranging in size from 10 users to over 10 million users.

**Comment by mheily** [comment]
Thanks @arr2036 for making me aware of the outstanding items that need to be addressed with libkqueue. I apologize for the long delay in responding to PRs, and would like to offer a quick explanation of what happened and what I plan to do going forward.

Some of the reasons for the lack of attention to libkqueue include:
* Increasing workload at $DAY_JOB has left less time for open source projects in general
* I rarely spend time in GitHub looking for things to do related to my older projects
* Other open source projects have attracted my attention, leaving less time for libkqueue specifically
* Switching all my personal computers over to FreeBSD made it harder to develop libkqueue, due to lack of a development and test environment.

Here's what I plan to do going forward:
* In the next week, I will review the backlog of PRs and take action on all of them.
* I will create a personal Linux development environment, probably as a virtual machine.
* I will cut a new release of libkqueue that incorporates all of the fixes that have been contributed since the last release.

**Comment by arr2036** [comment]
@mheily thanks for the response.  I absolutely understand what it's like having legacy projects hanging around.  You've moved on but there's still a community that find it useful and bug you for things.

If you ever want assistance in dealing with pull requests (maybe after there have been a few more PRs that you're happy with) then let me know and I'd be glad to step up.

> - In the next week, I will review the backlog of PRs and take action on all of them.
> - I will create a personal Linux development environment, probably as a virtual machine.
> - I will cut a new release of libkqueue that incorporates all of the fixes that have been contributed since the last release.

That sounds great, thanks!

Out of the PRs that we've contributed: https://github.com/mheily/libkqueue/pull/33 is the most contentious.  I'm honestly not sure if this is correct fix or not.  We have worked around it internally, but it'd be good to get a proper fix into libkqueue, as libkqueue in its current state is completely non-functional with libpcap.  We needed a fix because it affects our DHCP module and packet analysis utilities.

Regarding cutting a new release, I don't know what the cmake packaging state is for Debian, if you find it's unusable and don't want to deal with the horrors of cmake packaging, ping me, and i'll find some time next week to sort it out.  We run support both, but the immediate need was to generate sane RPMs on RedHat/Centos so that got the fixups https://github.com/mheily/libkqueue/pull/34 first.

**Comment by mheily** [comment]
@arr2036 I've merged all the pull requests and tagged a v2.2.0 release. I've also sent you an invitation to become a committer to this project. Thanks for offering to help o ut.
Regarding the CMake packaging question, would you mind working on that? I don't care to learn CPack at this time. I'll submit an updated Debian package upstream, and see about submitting something to Fedora/EPEL. I'm considering using the opensuse build/packacking system to publish semi-official packages.

**Comment by arr2036** [comment]
> @arr2036 I've merged all the pull requests and tagged a v2.2.0 release. I've also sent you an invitation to become a committer to this project. Thanks for offering to help o ut.

Accepted, thanks!

> Regarding the CMake packaging question, would you mind working on that? I don't care to learn CPack at this time. I'll submit an updated Debian package upstream, and see about submitting something to Fedora/EPEL. I'm considering using the opensuse build/packacking system to publish semi-official packages.

Yep absolutely.

There were a few maintenance things I was going to crack on with but wanted to check with you.

Currently, the project doesn't seem to have any kind of CIT integration.  Mind if I set it up with Travis?  That way the existing test suite gets run on new PRs and whenever anyone pushes to the repo.

Formatting is not always consistent especially with the windows code.  I can try and come up with some rules based on the general style of the code and run it through an automated formatter?

Are you adverse to Doxygen (code documentation tool)? We tend to use this style of function headers https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/src/lib/ldap/connection.c#L196.  One of the nice things about Doxygen is clang can perform validation of the Doxygen headers, and warn you when they don't match the observed arguments.

**Comment by mheily** [comment]
On Nov 27, 2017 09:31, "Arran Cudbard-Bell" <notifications@github.com>
wrote:

@arr2036 <https://github.com/arr2036> I've merged all the pull requests and
tagged a v2.2.0 release. I've also sent you an invitation to become a
committer to this project. Thanks for offering to help o ut.

Accepted, thanks!

Regarding the CMake packaging question, would you mind working on that? I
don't care to learn CPack at this time. I'll submit an updated Debian
package upstream, and see about submitting something to Fedora/EPEL. I'm
considering using the opensuse build/packacking system to publish
semi-official packages.

Yep absolutely.

There were a few maintenance things I was going to crack on with but wanted
to check with you.

Currently, the project doesn't seem to have any kind of CIT integration.
Mind if I set it up with Travis? That way the existing test suite gets run
on new PRs and whenever anyone pushes to the repo.

+1 go for it

Formatting is not always consistent especially with the windows code. I can
try and come up with some rules based on the general style of the code and
run it through an automated formatter?

I've read that it's risky to do bulk formatting changes, but have never
tried it personally. I'm okay with it as long as there are no other changes
mixed in with the style changes.

Are you adverse to Doxygen (code documentation tool)? We tend to use this
style of function headers https://github.com/FreeRADIUS/
freeradius-server/blob/v4.0.x/src/lib/ldap/connection.c#L196. One of the
nice things about Doxygen is clang can perform validation of the Doxygen
headers, and warn you when they don't match the observed arguments.

Neat, I didn't know that. I'm fine with using Doxygen comments.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mheily/libkqueue/issues/40#issuecomment-347198322>, or mute
the thread

**Comment by arr2036** [comment]
OK, there's now a ``.travis.yml`` file in the repo (tested on my repo: https://travis-ci.org/arr2036/libkqueue/builds/308392873).  You just need to turn on Travis builds for this repo at https://travis-ci.org/.  You should be able to login with your GitHub credentials.

**Comment by mheily** [comment]
Thanks! I turned on Travis CI integration and verified that it is working.

https://travis-ci.org/mheily/libkqueue

**Comment by arr2036** [comment]
@mheily, @mcnewton has now fixed the build process for Debian packages, thanks @mcnewton!

Would you agree to a 3.2.1 release, and submitting the new packages to Debian?

**Comment by mcnewton** [comment]
@arr2036 @mheily I have just also finished updating the Debian packaging in the debian-packages repo, which is now building packages of 2.3.0. I will test that they work correctly tomorrow and then do a PR. Hopefully that will make it easier to push new packages to the main Debian repo.

**Comment by mcnewton** [comment]
Debian packaging for libkqueue updated: https://github.com/mheily/debian-packages/pull/1
